first version
Cercosa/Twitter_semantic_analysis pull request #1
Opened 2020-10-07 12:24 UTC by Cercosa

2020-10-08 14:17 UTC, Kvm99 requested changes

2020-10-08 14:17 UTC, Kvm99 commented on settings.py
> +API_key = 'CZh46Yk3nrFZij7gZq7DDw'
секретные ключи очень не рекомендуется добавлять в репозиторий (об этом говорилась на первом уроке про токены к первому боту)

2020-10-08 14:17 UTC, Kvm99 commented on hashtag_mining.py
> +for tweet in tweepy.Cursor(api.search, q=hashtag, rpp=100).items():
нужно эту часть (про получение твитов) вынести в функцию

2020-10-08 14:17 UTC, Kvm99 commented on hashtag_mining.py
> +hashtag = input('Input your hashtag starting with "#"', )
вынести в ```if __name__=="__main__"```

2020-10-08 14:17 UTC, Kvm99 commented on hashtag_mining.py
> +
добавить ```if __name__==...``` сделать там получение введенных данных от пользователя, передать его в фенкцию по получению твитов, вызвать ее

2020-10-09 08:14 UTC, Cercosa commented on settings.py
> +API_key = 'CZh46Yk3nrFZij7gZq7DDw'
удалила

2020-10-26 08:31 UTC, Kvm99 commented on machin_learning_2.py
> +if __name__ == "__main__":
зачем это тут, если оно ничего не делает?

2020-10-26 08:31 UTC, Kvm99 commented on machin_learning_2.py
> +if __name__ == "__main__":
зачем тут ```if __name__ ... ``` если оно ничего не делает?

2020-10-27 09:48 UTC, merged